# see reference https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters:
  disable-all: true   # only enable the linters that are explicitly enabled
  enable:
    - errcheck
    - errorlint
    - goconst
    - gocognit
    - gocyclo
    - godot
    - godox
    - gofumpt
    - gosec
    - govet
    - ireturn
    - misspell
    - nestif
    - nosprintfhostport
    - staticcheck
    - testpackage
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 10

output:
  format: "colored-line-number,json:golangci-lint.report.json"
  print-linter-name: true
  sort-results: true
